DAC6-2859 : Content changes
hmrc/register-country-by-country-reporting-frontend pull request #118
Opened 2023-12-05 13:41 UTC by AashuChauhanHmrc

2023-12-06 15:34 UTC, matthewharris1 requested changes

2023-12-06 16:03 UTC, matthewharris1 approved these changes

2023-12-08 17:14 UTC, chriswaugh requested changes

2023-12-11 16:44 UTC, AashuChauhanHmrc commented on test/controllers/IsThisYourBusinessControllerSpec.scala
> +        contentAsString(result) mustEqual view(corporationTaxEnquiries , startUrl , Some(LimitedCompany))(request, messages(application)).toString
Hi Chris , For this as the tests are passing. do we need to make this change?

2023-12-12 10:58 UTC, chriswaugh commented on test/controllers/IsThisYourBusinessControllerSpec.scala
> +        contentAsString(result) mustEqual view(corporationTaxEnquiries , startUrl , Some(LimitedCompany))(request, messages(application)).toString
We had a little look into this and it wasn't as quick or straight forward as I hoped. Don't want to hold this work back on account of some pre-existing work needing refactoring - we can raise that as a separate tech debt ticket and come back to it later.

2023-12-12 10:59 UTC, chriswaugh submitted a review, later dismissed

2023-12-12 12:56 UTC, chriswaugh approved these changes

2023-12-12 13:34 UTC, merged